"use client";

import { useMemo, useState } from "react";
import { humanizeStatus, type RecruitmentEntityType } from "@/lib/recruitment-operations";

type Recruiter = { id:string; name:string; email:string; role?:string|null; active:boolean };
type RecordItem = { id:string; status?:string|null; assigned_recruiter_id?:string|null; full_name?:string|null; email?:string|null; company_name?:string|null; contact_name?:string|null; job_title_snapshot?:string|null; job_roles?:string|null; target_roles?:string|null };
type Interview = { id:string; application_id:string; recruiter_id?:string|null; starts_at:string; duration_minutes:number; timezone:string; format:"video"|"phone"|"in_person"; location?:string|null; meeting_url?:string|null; status:"scheduled"|"completed"|"cancelled"|"no_show"; notes?:string|null };
type Props = { applications:RecordItem[]; employers:RecordItem[]; talent:RecordItem[]; recruiters:Recruiter[]; interviews:Interview[] };
type AssignmentKind = "applications"|"employers"|"talent";

const entityFor = (kind:AssignmentKind):RecruitmentEntityType => kind === "applications" ? "job_application" : kind === "employers" ? "employer_request" : "talent_network";
const labelFor = (kind:AssignmentKind, item:RecordItem) => kind === "employers" ? item.company_name || item.contact_name || "Employer request" : item.full_name || "Candidate";
const contextFor = (kind:AssignmentKind, item:RecordItem) => kind === "applications" ? item.job_title_snapshot || "Application" : kind === "employers" ? item.job_roles || "Hiring request" : item.target_roles || "Talent profile";
const localInputValue = (iso:string) => { const date = new Date(iso); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60000).toISOString().slice(0,16); };
const icsDate = (iso:string) => new Date(iso).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");
const escapeIcsText = (value:string) => value.replace(/\\/g,"\\\\").replace(/\r?\n/g,"\\n").replace(/;/g,"\\;").replace(/,/g,"\\,");

export default function RecruiterSchedulingClient({applications,employers,talent,recruiters,interviews}:Props){
 const[recruiterRows,setRecruiterRows]=useState(recruiters),[applicationRows,setApplicationRows]=useState(applications),[employerRows,setEmployerRows]=useState(employers),[talentRows,setTalentRows]=useState(talent),[interviewRows,setInterviewRows]=useState(interviews),[kind,setKind]=useState<AssignmentKind>("applications"),[selected,setSelected]=useState<string[]>([]),[assignment,setAssignment]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[showInactive,setShowInactive]=useState(false),[newRecruiter,setNewRecruiter]=useState({name:"",email:"",role:""}),[interviewApplication,setInterviewApplication]=useState(""),[interviewForm,setInterviewForm]=useState({startsAt:localInputValue(new Date(Date.now()+86400000).toISOString()),durationMinutes:30,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",format:"video",location:"",meetingUrl:"",recruiterId:"",notes:""});
 const rows=kind==="applications"?applicationRows:kind==="employers"?employerRows:talentRows;
 const activeRecruiters=recruiterRows.filter(r=>r.active);
 const upcoming=useMemo(()=>interviewRows.filter(i=>i.status==="scheduled"&&new Date(i.starts_at)>=new Date()).sort((a,b)=>a.starts_at.localeCompare(b.starts_at)),[interviewRows]);
 const workloads=useMemo(()=>recruiterRows.map(r=>({recruiter:r,count:[...applicationRows,...employerRows,...talentRows].filter(i=>i.assigned_recruiter_id===r.id).length})).sort((a,b)=>b.count-a.count),[recruiterRows,applicationRows,employerRows,talentRows]);
 function updateLocal(ids:string[],recruiterId:string|null){const updater=(current:RecordItem[])=>current.map(item=>ids.includes(item.id)?{...item,assigned_recruiter_id:recruiterId}:item);if(kind==="applications")setApplicationRows(updater);if(kind==="employers")setEmployerRows(updater);if(kind==="talent")setTalentRows(updater)}
 async function assign(){if(!selected.length)return;setSaving(true);setMessage("");const recruiterId=assignment||null;const results=await Promise.all(selected.map(async id=>(await fetch("/api/admin/recruitment",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({entityType:entityFor(kind),id,assignedRecruiterId:recruiterId})})).ok));const successful=selected.filter((_,i)=>results[i]);updateLocal(successful,recruiterId);setSelected(selected.filter(id=>!successful.includes(id)));setSaving(false);setMessage(results.every(Boolean)?`${successful.length} assignment${successful.length===1?"":"s"} updated.`:`${successful.length} updated; ${results.length-successful.length} failed.`)}
 async function addRecruiter(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");const response=await fetch("/api/admin/recruiters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(newRecruiter)}),result=await response.json().catch(()=>null);setSaving(false);if(!response.ok)return setMessage(result?.error||"Unable to add recruiter.");setRecruiterRows(cur=>[...cur,result.recruiter].sort((a,b)=>a.name.localeCompare(b.name)));setNewRecruiter({name:"",email:"",role:""});setMessage("Recruiter added.")}
 async function toggleRecruiter(recruiter:Recruiter){const response=await fetch("/api/admin/recruiters",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:recruiter.id,active:!recruiter.active})}),result=await response.json().catch(()=>null);if(!response.ok)return setMessage(result?.error||"Unable to update recruiter.");setRecruiterRows(cur=>cur.map(r=>r.id===recruiter.id?result.recruiter:r));setMessage(result.recruiter.active?"Recruiter activated.":"Recruiter deactivated.")}
 async function scheduleInterview(e:React.FormEvent){e.preventDefault();if(!interviewApplication)return;setSaving(true);setMessage("");const startsAt=new Date(interviewForm.startsAt).toISOString();const response=await fetch("/api/admin/interviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({applicationId:interviewApplication,recruiterId:interviewForm.recruiterId||null,startsAt,durationMinutes:Number(interviewForm.durationMinutes),timezone:interviewForm.timezone,format:interviewForm.format,location:interviewForm.location,meetingUrl:interviewForm.meetingUrl,notes:interviewForm.notes})}),result=await response.json().catch(()=>null);setSaving(false);if(!response.ok)return setMessage(result?.error||"Unable to schedule interview.");setInterviewRows(cur=>[...cur,result.interview]);setInterviewApplication("");setInterviewForm(cur=>({...cur,startsAt:localInputValue(new Date(Date.now()+86400000).toISOString()),location:"",meetingUrl:"",notes:""}));setMessage("Interview scheduled.")}
 async function updateInterview(interview:Interview,status:Interview["status"]){const response=await fetch("/api/admin/interviews",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:interview.id,status})}),result=await response.json().catch(()=>null);if(!response.ok)return setMessage(result?.error||"Unable to update interview.");setInterviewRows(cur=>cur.map(i=>i.id===interview.id?result.interview:i));setMessage(`Interview marked ${humanizeStatus(status).toLowerCase()}.`)}
 function downloadCalendar(interview:Interview){const application=applicationRows.find(a=>a.id===interview.application_id),recruiter=recruiterRows.find(r=>r.id===interview.recruiter_id),end=new Date(new Date(interview.starts_at).getTime()+interview.duration_minutes*60000).toISOString(),description=[`Candidate: ${application?.full_name||"Candidate"}`,`Role: ${application?.job_title_snapshot||"Opportunity"}`,recruiter?`Recruiter: ${recruiter.name}`:"",interview.meeting_url||""].filter(Boolean).join("\n"),summary=`Circle Wave interview - ${application?.full_name||"Candidate"}`,location=interview.location||interview.meeting_url||"",content=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Circle Wave//Recruitment//EN","BEGIN:VEVENT",`UID:${interview.id}@circlewave`,`DTSTAMP:${icsDate(new Date().toISOString())}`,`DTSTART:${icsDate(interview.starts_at)}`,`DTEND:${icsDate(end)}`,`SUMMARY:${escapeIcsText(summary)}`,`DESCRIPTION:${escapeIcsText(description)}`,`LOCATION:${escapeIcsText(location)}`,"END:VEVENT","END:VCALENDAR"].join("\r\n"),url=URL.createObjectURL(new Blob([content],{type:"text/calendar;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=`circle-wave-interview-${interview.id}.ics`;a.click();URL.revokeObjectURL(url)}
 function invitationLink(interview:Interview){const application=applicationRows.find(a=>a.id===interview.application_id),recruiter=recruiterRows.find(r=>r.id===interview.recruiter_id),when=new Date(interview.starts_at).toLocaleString(undefined,{dateStyle:"full",timeStyle:"short",timeZone:interview.timezone}),details=interview.format==="video"?interview.meeting_url||"Video meeting details will follow.":interview.format==="phone"?"This interview will take place by phone.":interview.location||"Location details will follow.",subject=encodeURIComponent(`Interview details for ${application?.job_title_snapshot||"your Circle Wave application"}`),body=encodeURIComponent(`Hello ${application?.full_name||"there"},\n\nYour Circle Wave interview is scheduled for ${when} (${interview.timezone}).\n\nFormat: ${humanizeStatus(interview.format)}\n${details}\nDuration: ${interview.duration_minutes} minutes\n${recruiter?`Recruiter: ${recruiter.name}\n`:""}\nPlease reply to confirm your availability.\n\nBest,\nCircle Wave`);return `mailto:${application?.email||""}?subject=${subject}&body=${body}`}
 return <div className="mt-10 grid gap-8">
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">Team management</p><h2 className="mt-2 text-2xl font-bold">Recruiters and workload</h2></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/>Show inactive</label></div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{workloads.filter(i=>showInactive||i.recruiter.active).map(({recruiter,count})=><article key={recruiter.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{recruiter.name}</h3><p className="text-sm text-slate-500">{recruiter.email}</p><p className="mt-1 text-xs text-slate-400">{recruiter.role||"Recruiter"}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${recruiter.active?"bg-emerald-100 text-emerald-700":"bg-slate-200 text-slate-600"}`}>{recruiter.active?"Active":"Inactive"}</span></div><p className="mt-4 text-2xl font-bold">{count}</p><p className="text-xs text-slate-500">assigned records</p><button onClick={()=>toggleRecruiter(recruiter)} className="mt-4 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">{recruiter.active?"Deactivate":"Activate"}</button></article>)}{!workloads.length&&<p className="rounded-2xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">No recruiters yet. Add the first recruiter using the form.</p>}</div><form onSubmit={addRecruiter} className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold">Add recruiter</h3><div className="mt-4 grid gap-3"><input required className="input" placeholder="Full name" value={newRecruiter.name} onChange={e=>setNewRecruiter({...newRecruiter,name:e.target.value})}/><input required type="email" className="input" placeholder="Email" value={newRecruiter.email} onChange={e=>setNewRecruiter({...newRecruiter,email:e.target.value})}/><input className="input" placeholder="Role (optional)" value={newRecruiter.role} onChange={e=>setNewRecruiter({...newRecruiter,role:e.target.value})}/><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-50">Add recruiter</button></div></form></div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">Assignments</p><h2 className="mt-2 text-2xl font-bold">Assign recruitment records</h2><div className="mt-5 flex flex-wrap gap-2">{(["applications","employers","talent"] as AssignmentKind[]).map(item=><button key={item} onClick={()=>{setKind(item);setSelected([])}} className={`rounded-xl px-4 py-2 text-sm font-semibold ${kind===item?"bg-slate-900 text-white":"border border-slate-200"}`}>{humanizeStatus(item)}</button>)}</div><div className="mt-5 flex flex-wrap items-center gap-3"><select className="input max-w-sm" value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="">Unassigned</option>{activeRecruiters.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button disabled={!selected.length||saving} onClick={assign} className="rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-50">Assign {selected.length||"selected"}</button><button onClick={()=>setSelected(rows.map(r=>r.id))} className="rounded-xl border border-slate-300 px-4 py-3 font-semibold">Select all</button><button onClick={()=>setSelected([])} className="rounded-xl border border-slate-300 px-4 py-3 font-semibold">Clear</button></div><div className="mt-5 overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Select</th><th className="px-4 py-3">Record</th><th className="px-4 py-3">Context</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Recruiter</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(item=>{const recruiter=recruiterRows.find(r=>r.id===item.assigned_recruiter_id);return <tr key={item.id}><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>setSelected(cur=>cur.includes(item.id)?cur.filter(id=>id!==item.id):[...cur,item.id])}/></td><td className="px-4 py-3 font-semibold">{labelFor(kind,item)}</td><td className="px-4 py-3">{contextFor(kind,item)}</td><td className="px-4 py-3">{humanizeStatus(item.status)}</td><td className="px-4 py-3">{recruiter?.name||"Unassigned"}</td></tr>})}</tbody></table></div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">Interview scheduling</p><h2 className="mt-2 text-2xl font-bold">Schedule an interview</h2><form onSubmit={scheduleInterview} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select required className="input" value={interviewApplication} onChange={e=>setInterviewApplication(e.target.value)}><option value="">Choose candidate</option>{applicationRows.map(a=><option key={a.id} value={a.id}>{a.full_name||"Candidate"} — {a.job_title_snapshot||"Opportunity"}</option>)}</select><input required type="datetime-local" className="input" value={interviewForm.startsAt} onChange={e=>setInterviewForm({...interviewForm,startsAt:e.target.value})}/><input required className="input" placeholder="Timezone" value={interviewForm.timezone} onChange={e=>setInterviewForm({...interviewForm,timezone:e.target.value})}/><select className="input" value={interviewForm.recruiterId} onChange={e=>setInterviewForm({...interviewForm,recruiterId:e.target.value})}><option value="">No recruiter</option>{activeRecruiters.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input required type="number" min="10" max="480" className="input" value={interviewForm.durationMinutes} onChange={e=>setInterviewForm({...interviewForm,durationMinutes:Number(e.target.value)})}/><select className="input" value={interviewForm.format} onChange={e=>setInterviewForm({...interviewForm,format:e.target.value})}><option value="video">Video</option><option value="phone">Phone</option><option value="in_person">In person</option></select><input className="input" placeholder="Location" value={interviewForm.location} onChange={e=>setInterviewForm({...interviewForm,location:e.target.value})}/><input type="url" className="input" placeholder="Meeting URL" value={interviewForm.meetingUrl} onChange={e=>setInterviewForm({...interviewForm,meetingUrl:e.target.value})}/><textarea className="input min-h-24 md:col-span-2 xl:col-span-3" placeholder="Internal interview notes" value={interviewForm.notes} onChange={e=>setInterviewForm({...interviewForm,notes:e.target.value})}/><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-50">Schedule interview</button></form></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">Calendar</p><h2 className="mt-2 text-2xl font-bold">Upcoming interviews</h2><div className="mt-5 grid gap-4">{upcoming.map(interview=>{const application=applicationRows.find(a=>a.id===interview.application_id),recruiter=recruiterRows.find(r=>r.id===interview.recruiter_id);return <article key={interview.id} className="rounded-2xl border border-slate-200 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h3 className="font-bold">{application?.full_name||"Candidate"}</h3><p className="text-sm text-slate-500">{application?.job_title_snapshot||"Opportunity"}</p><p className="mt-3 text-sm">{new Date(interview.starts_at).toLocaleString()} · {interview.duration_minutes} minutes · {humanizeStatus(interview.format)}</p><p className="mt-1 text-sm text-slate-500">{recruiter?.name||"No recruiter assigned"} · {interview.timezone}</p>{(interview.location||interview.meeting_url)&&<p className="mt-1 text-sm text-slate-500">{interview.meeting_url||interview.location}</p>}</div><div className="flex flex-wrap gap-2"><a href={invitationLink(interview)} className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white">Email invitation</a><button onClick={()=>downloadCalendar(interview)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Download .ics</button><button onClick={()=>updateInterview(interview,"completed")} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Complete</button><button onClick={()=>updateInterview(interview,"cancelled")} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Cancel</button></div></div></article>})}{!upcoming.length&&<p className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No upcoming interviews scheduled.</p>}</div></section>
  {message&&<div role="status" className="fixed bottom-5 right-5 z-50 rounded-2xl bg-slate-900 px-5 py-4 text-sm font-semibold text-white shadow-2xl">{message}</div>}
 </div>
}
